[package]
name = "client"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "client"
path = "main.rs"

[dependencies]
common = { path = "../common" }

anyhow.workspace = true
futures.workspace = true
tokio.workspace = true
zbus.workspace = true
