[package]
name = "airpods-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
btleplug = "0.11.8"
futures = "0.3.31"
tokio = { version = "1.46.1", features = ["full"] }
uuid = "1.17.0"
